### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xinyu-jon** [TL-System/plato#308]
**Describe the bug**
```python
      self.client_partition = sampler_utils.create_dirichlet_skew(
          total_size=total_data_size,
          concentration=client_quantity_concentration,
          min_partition_size=None,
          number_partitions=total_clients,
      )[client_id]
```
There is a bug in line 77 of plato/plato/samplers/distribution_noniid.py: it is out of bounds. When there are 10 client nodes, it will try to access the element with index 10.

**To Reproduce**
Use config.yaml like this
```yaml
data:
    # The training and testing dataset
    datasource: MNIST

    # Where the dataset is located
    data_path: ../../data

    # IID or non-IID?
    sampler: distribution_noniid

    client_quantity_concentration: 0.4

    min_partition_size: 50


    # The random seed for sampling data
    random_seed: 1
```

**Expected behavior**
Runs normally

**Screenshots**
![24a38d01e27595319cb121ba0fbf3a6](https://user-images.githubusercontent.com/87824183/233018657-88e992fa-bc80-4357-9a41-a7c45f83c2a3.jpg)

**OS environment (please complete the following information):**
 - OS:  Linux
 - Version: Lastest
