### ISSUE TITLE
[BUG] `consistent_clients` config not works in `sampler: mixed_label_quantity_noniid`

### ISSUE THREAD

**Issue by luuvy757** [TL-System/plato#355]
**Describe the bug**

When using `mixed_label_quantity_noniid` sampler, the `consistent_clients` does not work. 
The following is the configuration of `data`:

```yaml
data:
    # The training and testing dataset
    datasource: MNIST
    # Number of samples in each partition
    partition_size: 100
    sampler: mixed_label_quantity_noniid 
    per_client_classes_size: 3
    anchor_classes: [3, 4, 9]
    consistent_clients: [1, 2]
    keep_anchor_classes_size: 1
    num_classes: 10
    random_seed: 1
```

**To Reproduce**

Obviously, [This line of code](https://github.com/TL-System/plato/blob/68de367fee165eb4089fec8cbe7c428563e97c90/plato/samplers/mixed_label_quantity_noniid.py#L60) 
only randomly sample `consistent_clients` from all clients, rather than set `consistent_clients` with the *configuration*.

**Expected behavior**
The expected assigned classes to client 1 and client 2 should be [3, 4, 9].

**Additional context**
The use of `client_id ` is confusing [ref](https://github.com/TL-System/plato/blob/68de367fee165eb4089fec8cbe7c428563e97c90/plato/samplers/sampler_utils.py#L102). 
The original usage of `consistent_clients` considers index-based (client_id-1) rather than `client_id`. 
That leads to confusion about the inconsistency of `client_id` in the context.
